[tool.poetry]
name = "forward_netbox"
version = "4.3.0"
description = "NetBox plugin to sync Forward data into NetBox"
authors = ["Solution Architecture <solution.architecture@forwardnetworks.com>"]
license = "MIT"
readme = "README.md"
repository = "https://forwardnetworks.com"
homepage = "https://forwardnetworks.com"
keywords = ["netbox", "forward", "plugin", "sync"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
packages = [{include = "forward_netbox"}]
include = [
    # The path must be inside the package directory, but we also need hardlink inside scripts/
    # This is because forward_netbox<=3.1.3 uses link to git repo to main to this file.
    { path = "forward_netbox/data/transform_map.json", format = ["sdist", "wheel"] }
]

[tool.poetry.dependencies]
python = "^3.10"
netboxlabs-netbox-branching = "0.7.0"
netutils = "*"

[tool.poetry.urls]
"Bug Tracker" = "https://forwardnetworks.com/support"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
invoke = "^2.2.0"
pre-commit = "^4.0.1"
python-dotenv = "^1.0.1"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
