# Generated by Django 5.2.6 on 2025-10-10 22:23

import json

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models
from importlib import resources


def load_default_nqe_queries(apps, schema_editor):
    ForwardNQEQuery = apps.get_model("forward_netbox", "ForwardNQEQuery")
    ContentType = apps.get_model("contenttypes", "ContentType")

    try:
        defaults = json.loads(
            resources.files("forward_netbox.data")
            .joinpath("nqe_map.json")
            .read_text(encoding="utf-8")
        )
    except FileNotFoundError:
        defaults = {}

    content_types = {
        f"{ct.app_label}.{ct.model}": ct
        for ct in ContentType.objects.filter(app_label__in=["dcim", "ipam"])
    }

    for model_label, meta in defaults.items():
        content_type = content_types.get(model_label)
        if not content_type:
            continue
        ForwardNQEQuery.objects.update_or_create(
            content_type=content_type,
            defaults={
                "query_id": meta.get("query_id", ""),
                "enabled": meta.get("enabled", True),
                "description": meta.get("description", ""),
            },
        )


def unload_default_nqe_queries(apps, schema_editor):
    ForwardNQEQuery = apps.get_model("forward_netbox", "ForwardNQEQuery")
    ForwardNQEQuery.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('forward_netbox', '0002_remove_transform_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardNQEQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('query_id', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('content_type', models.OneToOneField(limit_choices_to=models.Q(('app_label', 'dcim'), ('app_label', 'ipam'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Forward Networks NQE Query',
                'verbose_name_plural': 'Forward Networks NQE Queries',
                'ordering': ('content_type__app_label', 'content_type__model'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.RunPython(load_default_nqe_queries, unload_default_nqe_queries),
    ]
