# Generated by Django 4.1.10 on 2024-01-09 16:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("forward_netbox", "0003_forwardsource_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="forwardsync",
            name="auto_merge",
            field=models.BooleanField(default=False),
        ),
    ]
