# Generated by Django 5.2.6 on 2025-10-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forward_netbox', '0002_remove_forwardsource_type'),
        ('forward_netbox', '0004_forwardsource_network_id'),
    ]

    operations = [
    ]
