# Generated by Django 6.0.4 on 2026-05-05
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("forward_netbox", "0008_alter_forwardnqemap_netbox_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forwardnqemap",
            name="netbox_model",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "dcim"), ("model", "site")),
                    models.Q(("app_label", "dcim"), ("model", "manufacturer")),
                    models.Q(("app_label", "dcim"), ("model", "devicerole")),
                    models.Q(("app_label", "dcim"), ("model", "platform")),
                    models.Q(("app_label", "dcim"), ("model", "devicetype")),
                    models.Q(("app_label", "dcim"), ("model", "device")),
                    models.Q(("app_label", "dcim"), ("model", "virtualchassis")),
                    models.Q(("app_label", "extras"), ("model", "taggeditem")),
                    models.Q(("app_label", "dcim"), ("model", "interface")),
                    models.Q(("app_label", "dcim"), ("model", "cablebundle")),
                    models.Q(("app_label", "dcim"), ("model", "cable")),
                    models.Q(("app_label", "dcim"), ("model", "macaddress")),
                    models.Q(("app_label", "ipam"), ("model", "vlan")),
                    models.Q(("app_label", "ipam"), ("model", "vrf")),
                    models.Q(("app_label", "ipam"), ("model", "prefix")),
                    models.Q(("app_label", "ipam"), ("model", "ipaddress")),
                    models.Q(("app_label", "dcim"), ("model", "inventoryitem")),
                    models.Q(("app_label", "dcim"), ("model", "module")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
