# Generated by Django 5.2.13 on 2026-05-07 02:24
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("forward_netbox", "0009_alter_forwardnqemap_netbox_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="forwardvalidationrun",
            name="override_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="forwardvalidationrun",
            name="override_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forwardvalidationrun",
            name="override_blocking_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="forwardvalidationrun",
            name="override_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="forwardvalidationrun",
            name="override_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
