# Generated by Django 5.2 on 2025-08-25 12:53
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "forward_netbox",
            "0017_forwardsync_update_custom_fields",
        ),
    ]
    operations = [
        migrations.RemoveField(
            model_name="forwardsync",
            name="type",
        ),
    ]
