# Generated by Django 5.2.13 on 2026-05-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forward_netbox', '0018_execution_run_reconciliation_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardexecutionstep',
            name='query_parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
