# Generated by Django 5.2.5 on 2025-09-22 07:43
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forward_netbox", "0018_remove_type_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forwardtransformmap",
            options={"ordering": ("pk",)},
        ),
        migrations.AlterModelOptions(
            name="forwardtransformmapgroup",
            options={"ordering": ("pk",)},
        ),
    ]
