# Generated by Django 6.0.5 on 2026-06-19 10:30
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("forward_netbox", "0023_split_ip_address_maps"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForwardDeviceAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("device_name", models.CharField(db_index=True, max_length=255)),
                ("reachable", models.BooleanField(default=False)),
                ("blast_radius", models.PositiveIntegerField(default=0)),
                ("cve_count", models.PositiveIntegerField(default=0)),
                ("up_interfaces", models.PositiveIntegerField(default=0)),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                (
                    "snapshot_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "sync",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_analyses",
                        to="forward_netbox.forwardsync",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forward Device Analysis",
                "verbose_name_plural": "Forward Device Analyses",
                "db_table": "forward_netbox_device_analysis",
                "ordering": ("device_name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sync", "device_name"),
                        name="forward_device_analysis_sync_device",
                    )
                ],
            },
        ),
    ]
