# Generated by Django 6.0.6 on 2026-06-22 13:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("forward_netbox", "0026_forwarddeviceanalysis_collection_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forwardexecutionrun",
            name="backend",
            field=models.CharField(default="single_branch", max_length=30),
        ),
    ]
