# Generated by Django 6.0.6 on 2026-06-22 14:52
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forward_netbox", "0027_alter_forwardexecutionrun_backend"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="forwardexecutionstep",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="forwardexecutionstep",
            name="run",
        ),
        migrations.RemoveField(
            model_name="forwardexecutionstep",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="forwardexecutionstep",
            name="ingestion",
        ),
        migrations.RemoveField(
            model_name="forwardexecutionstep",
            name="job",
        ),
        migrations.RemoveField(
            model_name="forwardexecutionstep",
            name="merge_job",
        ),
        migrations.DeleteModel(
            name="ForwardExecutionStep",
        ),
        migrations.DeleteModel(
            name="ForwardExecutionRun",
        ),
    ]
