# Generated by Django 6.0.6 on 2026-07-01 17:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("forward_netbox", "0029_forward_parent_device_cf"),
    ]

    operations = [
        migrations.AddField(
            model_name="forwarddeviceanalysis",
            name="cve_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
