# Generated by Django 6.0.6 on 2026-07-09 21:57
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("forward_netbox", "0031_encrypt_source_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forwardnqemap",
            name="netbox_model",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "dcim"), ("model", "site")),
                    models.Q(("app_label", "dcim"), ("model", "manufacturer")),
                    models.Q(("app_label", "dcim"), ("model", "devicerole")),
                    models.Q(("app_label", "dcim"), ("model", "platform")),
                    models.Q(("app_label", "dcim"), ("model", "devicetype")),
                    models.Q(("app_label", "dcim"), ("model", "device")),
                    models.Q(("app_label", "dcim"), ("model", "virtualchassis")),
                    models.Q(("app_label", "extras"), ("model", "taggeditem")),
                    models.Q(("app_label", "dcim"), ("model", "interface")),
                    models.Q(("app_label", "dcim"), ("model", "cable")),
                    models.Q(("app_label", "dcim"), ("model", "macaddress")),
                    models.Q(("app_label", "ipam"), ("model", "vlan")),
                    models.Q(("app_label", "ipam"), ("model", "vrf")),
                    models.Q(("app_label", "ipam"), ("model", "prefix")),
                    models.Q(("app_label", "ipam"), ("model", "ipaddress")),
                    models.Q(("app_label", "ipam"), ("model", "fhrpgroup")),
                    models.Q(("app_label", "dcim"), ("model", "inventoryitem")),
                    models.Q(("app_label", "dcim"), ("model", "module")),
                    models.Q(("app_label", "netbox_routing"), ("model", "bgppeer")),
                    models.Q(
                        ("app_label", "netbox_routing"), ("model", "bgpaddressfamily")
                    ),
                    models.Q(
                        ("app_label", "netbox_routing"),
                        ("model", "bgppeeraddressfamily"),
                    ),
                    models.Q(
                        ("app_label", "netbox_routing"), ("model", "ospfinstance")
                    ),
                    models.Q(("app_label", "netbox_routing"), ("model", "ospfarea")),
                    models.Q(
                        ("app_label", "netbox_routing"), ("model", "ospfinterface")
                    ),
                    models.Q(
                        ("app_label", "netbox_peering_manager"),
                        ("model", "peeringsession"),
                    ),
                    models.Q(("app_label", "netbox_cisco_aci"), ("model", "acifabric")),
                    models.Q(("app_label", "netbox_cisco_aci"), ("model", "acipod")),
                    models.Q(("app_label", "netbox_cisco_aci"), ("model", "acinode")),
                    models.Q(("app_label", "netbox_cisco_aci"), ("model", "acitenant")),
                    models.Q(("app_label", "netbox_cisco_aci"), ("model", "acivrf")),
                    models.Q(
                        ("app_label", "netbox_cisco_aci"), ("model", "acibridgedomain")
                    ),
                    models.Q(
                        ("app_label", "netbox_cisco_aci"), ("model", "aciappprofile")
                    ),
                    models.Q(
                        ("app_label", "netbox_cisco_aci"), ("model", "aciendpointgroup")
                    ),
                    models.Q(
                        ("app_label", "netbox_cisco_aci"), ("model", "acicontract")
                    ),
                    models.Q(("app_label", "netbox_cisco_aci"), ("model", "acifilter")),
                    models.Q(("app_label", "netbox_cisco_aci"), ("model", "acil3out")),
                    models.Q(
                        ("app_label", "netbox_cisco_aci"),
                        ("model", "acistaticportbinding"),
                    ),
                    models.Q(("app_label", "netbox_dlm"), ("model", "softwareversion")),
                    models.Q(("app_label", "netbox_dlm"), ("model", "hardwarenotice")),
                    models.Q(("app_label", "netbox_dlm"), ("model", "devicesoftware")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
