# Generated by Django 6.0.7 on 2026-08-13 20:09
import django.db.models.deletion
from django.db import migrations
from django.db import models

import forward_netbox.models


class Migration(migrations.Migration):

    # `makemigrations` writes the newest dcim migration it can see, which was a
    # NetBox 4.6.6 one - so this migration could not be applied on 4.6.5 at all,
    # even though the plugin supports it. Shipped that way in 2.8.0 and caught by
    # the 2.8.1 upgrade gate, which is the first leg to install a plugin version
    # carrying this migration onto 4.6.5.
    #
    # All this actually needs is for `dcim.Device` to exist, so it depends on
    # dcim's initial migration like every other migration here does. Changing a
    # dependency does not re-run an applied migration; Django records those by
    # name, and the ordering still holds because 0001 precedes everything.
    dependencies = [
        ("dcim", "0001_initial"),
        ("forward_netbox", "0051_ownership_provenance_stamp_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForwardDeviceAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("consecutive_absent_runs", models.PositiveIntegerField(default=0)),
                ("first_absent_at", models.DateTimeField()),
                ("last_absent_at", models.DateTimeField()),
                (
                    "last_absent_snapshot_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="dcim.device",
                    ),
                ),
                (
                    "sync",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_absences",
                        to="forward_netbox.forwardsync",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forward Device Absence",
                "verbose_name_plural": "Forward Device Absences",
                "db_table": "forward_netbox_device_absence",
                "ordering": ("sync__name", "device__name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sync", "device"),
                        name="forward_device_absence_identity",
                    )
                ],
            },
            bases=(forward_netbox.models.ForwardPluginModelDocsMixin, models.Model),
        ),
    ]
