# Generated by Django 6.0.7 on 2026-08-13 20:09

import django.db.models.deletion
import forward_netbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('forward_netbox', '0051_ownership_provenance_stamp_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardDeviceAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('consecutive_absent_runs', models.PositiveIntegerField(default=0)),
                ('first_absent_at', models.DateTimeField()),
                ('last_absent_at', models.DateTimeField()),
                ('last_absent_snapshot_id', models.CharField(blank=True, default='', max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dcim.device')),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_absences', to='forward_netbox.forwardsync')),
            ],
            options={
                'verbose_name': 'Forward Device Absence',
                'verbose_name_plural': 'Forward Device Absences',
                'db_table': 'forward_netbox_device_absence',
                'ordering': ('sync__name', 'device__name'),
                'constraints': [models.UniqueConstraint(fields=('sync', 'device'), name='forward_device_absence_identity')],
            },
            bases=(forward_netbox.models.ForwardPluginModelDocsMixin, models.Model),
        ),
    ]
