# Generated by Django 6.1 on 2026-09-17 13:48
from django.db import migrations
from django.db import models

import forward_netbox.models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0001_initial"),
        ("forward_netbox", "0057_aci_tenant_policy_nqe_map_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forwarddeviceidentity",
            name="device",
            field=models.ForeignKey(
                on_delete=forward_netbox.models.release_on_operator_delete,
                related_name="+",
                to="dcim.device",
            ),
        ),
        migrations.AlterField(
            model_name="forwarddevicetagclaim",
            name="device",
            field=models.ForeignKey(
                on_delete=forward_netbox.models.release_on_operator_delete,
                related_name="+",
                to="dcim.device",
            ),
        ),
    ]
